run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Find commonly misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security problems
    - bodyclose     # Check HTTP response body is closed
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Unused function parameters
  disable:
    - typecheck     # Disable typecheck as it has issues with import resolution

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Ignore struct field alignment optimization

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "disableStutteringCheck"

  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)

issues:
  exclude-rules:
    # Exclude test files from certain checks
    - path: _test\.go
      linters:
        - errcheck  # Tests often intentionally ignore errors
        - gosec     # Security checks less critical in tests
        - unused    # Test helpers and fixtures may appear unused
        - unparam   # Test functions often have unused parameters
    # Exclude typecheck errors for import issues
    - linters:
        - typecheck
      text: "could not import|undefined:"

  max-issues-per-linter: 0
  max-same-issues: 0
